### ISSUE TITLE
Game spams `/SaveEvents2` during Freelancer gameplay

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#104]
[Reported](https://discord.com/channels/826809653181808651/826809653744762932/1069405622073823272) a few times. The game spams `/SaveEvents2` during Freelancer gameplay. This is observed more often after exiting the level and before the mission end scene. This bug has happened before on v4 during normal gameplay but I don't know how it was resolved or by whom. I have not been able to reproduce this bug.
![image](https://user-images.githubusercontent.com/118079569/216217279-52cecf20-7f37-44dc-bd52-111de0027a5f.png)

**Comment by LennardF1989** [comment]
I see this happen randomly at times. Perhaps we should introduce logic to make sure every event is always acknowledged, even if we don't use it. There is currently some logic in place to escape the event handler early on, and I'm pretty sure this causes this issue from time to time. Can't hurt to verify.

**Comment by moonysolari** [comment]
This has not happened to me at all. I think we should add more debug output around events so that we at least know what event the game is sending when it happens.

**Comment by moonysolari** [comment]
Closing this as completed by #190 and #191. Reopen if the problem reappears.

**Comment by Kronzky** [comment]
It's still happening fairly regularly, and in all kinds on game modes (Freelance, Exclusive Targets, etc.).
I don't see anything specific triggering it, but the error is always `"The \"path\" argument must be of type string. Received undefined"`, after some time of playing (half an hour or so).
Sometimes it recovers, quite often it doesn't.

I've attached the logs of three crashes.
[crashes.zip](https://github.com/thepeacockproject/Peacock/files/11374752/crashes.zip)

**Comment by AnthonyFuller** [comment]
Close the Peacock server. Then open `Tools.cmd`, press enter, then send the `DEBUG_PROFILE.zip` found in the Peacock directory.

**Comment by moonysolari** [comment]
> I've attached the logs of three crashes.

I think your problem was caused by a cracked version of Peacock.

**Comment by Kronzky** [comment]
> I think your problem was caused by a cracked version of Peacock.

The thing is, I'm trying to run this on a machine that has no Internet _at all_.
The stock Peacock is still connecting to the official servers at startup, so that won't work.

And I guess this error is caused by subsequent connection attempts during the game (which isn't an issue if you're connected anyway, but for a real offline machine this is causing problems).

I understand if you don't want to do support for a "cracked" versions, but to me it seems that still needing online access for running the game sort-of contradicts the purpose of this tool...

**Comment by AnthonyFuller** [comment]
It needs it once on first connect. And to launch the game anyway, you need to be online for Epic (and possibly even Steam). We are **not supporting cracked versions of Peacock** as the issue doesn't even exist on "official" versions of Peacock.

I'm locking this to contributors only as it's just pointless trying to diagnose an issue, that in our eyes, doesn't exist.
