### ISSUE TITLE
The Steam version of the game saves every 3 seconds on Peacock

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#105]
[Reported](https://discord.com/channels/826809653181808651/1069457034589769778) multiple times. 

Possibly caused by `/authentication/api/userchannel/ProfileService/GetPlatformEntitlements`. If the game is not satisfied with the response to this request, it will send this request again and again. Each time it sends this request, it will also send one `/authentication/api/userchannel/ProfileService/SynchronizeOfflineUnlockables` and one `/authentication/api/userchannel/ProfileService/UpdateUserSaveFileTable` request. The latter causes the "Saving..." banner to pop in the bottom-right corner of the game. 

Exactly what the game is looking for in the response of `GetPlatformEntitlements` is unknown. I succeeded in reproducing this bug if I set the response to an empty array. More investigation is needed.

**Comment by Arnauw** [comment]
Unless someone you trust has reproduced the issue I'm pretty sure it doesn't happen with legit steam version of the game.
