### ISSUE TITLE
Different Mastery progressions for different games

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#109]
All games currently have the same mastery items as H3 on Peacock. However, H1, H2 and H3 do not have the same mastery progression on every location. E.g. Hawkes Bay Lvl. 5 should not have Tanto in H2. 

Originally tracked in #90 .

**Comment by LennardF1989** [comment]
I think this is also related to #93, the same solution should be applied to this since it is in essence the same logic.
