### ISSUE TITLE
New DLCs are not displayed without deleting `userdata`

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#119]
When the user acquires new DLCs, Peacock will not know about it unless the user deletes `userdata`.

One solution is to get and overwrite the user's entitlements every time the user authenticates, and do not rely on past entitlement data.

**Comment by RDIL** [comment]
Go-ahead as long as this process aborts early in the case of any errors.

**Comment by alex73630** [comment]
+1

As long as there is a fail-safe if entitlements aren't available then I approve the solution 👍
