### ISSUE TITLE
Disconnections pop up out of nowhere

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#122]
From time to time, the game randomly pops up the "Disconnected" window. Pressing "retry" often fixes it and resumes the connection. When this happens is entirely unpredictable. 

Logging the requests and responses of `/api/metrics/add` calls yielded the following results. Credits to @fu5ha for considering this approach first.
``` json
{
    "Name": "PlayerDisconnected",
    "Properties": {
        "ProfileId": "moony",
        "ServerConfig": "pc-prod",
        "ServerVersion": "8.10.0",
        "ErrorCode": 12030,
        "ErrorState": 4,
        "ErrorString": "There was a network error. Please check your internet connection.",
        "FailedRequestUrl": "UpdateCheckNetworkStatus:http://127.0.0.1/authentication/api/userchannel/GamePersistentDataService/GetData",
        "ReconnectFailed": false,
        "PreviousState": 38,
        "RetryCount": 0,
        "SecondsSinceLastSuspendChanged": 4094.467285,
        "SuccessfulRequestsSinceLastSuspend": 156,
        "Scene": "assembly:/_PRO/Scenes/Frontend/MainMenu.entity",
        "InLoadTransition": false,
        "GameTime": 490.956329
    },
    "UserId": "moony",
    "PlatformUserId": "moony",
    "SessionId": "moony",
    "Agg": "20210107",
    "Platform": "epic",
    "Version": "8.10.0",
    "GameVersion": "3, 130, 0, 0",
    "Config": "pc-prod",
    "IssuerId": "moony",
    "GameMode": "normal"
}
```
[12030](https://learn.microsoft.com/en-us/windows/win32/winhttp/error-messages) is a WinHttp error code `ERROR_WINHTTP_CONNECTION_ERROR`. Across different disconnection instances, the error number has always been observed to be 12030, but the request url may vary.

It is possible that the problem is not how these requests are dealt with, it's that Peacock never got those requests in the first place. On this note, it is more likely a bug of the patcher.

**Comment by AnthonyFuller** [comment]
It is believed that this is due to the "allow HTTP" patch (as it's slightly hacky). One suggestion me and @RDIL both had is serving HTTPS with a self signed certificate generated "on the fly" by Peacock.

**Comment by AnthonyFuller** [comment]
Not had many reports of disconnections anymore... I wonder if IOI did something on their end.

**Comment by moonysolari** [comment]
I think it's either because people are used to it or the game is not popular anymore.

**Comment by AnthonyFuller** [comment]
You'd be surprised.

**Comment by thecatontheceiling** [comment]
experienced this issue for some time on v6.5.1 but after updating to latest version at the time of writing the issue is fixed

**Comment by AnthonyFuller** [comment]
Some time after v7 releases we'll look back into this.
