### ISSUE TITLE
Challenges with a progress bar do not save progress between runs

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#13]
Peacock version: 5.4.0
Game: Hitman III (Epic games)

Challenges with a progress bar that ought to save between runs (e.g. Chameleon, Versatile Assassin) do not save between runs.

**Comment by AnthonyFuller** [comment]
To add onto this: sometimes challenges will complete in-game as shown in the top left (and on the end screen meaning Peacock completed them), but they will still be sent and then re-completed in-game, I need to investigate this myself to make sure it's not something I've done as I've only noticed it on the EG branch.

**Comment by RDIL** [comment]
Partially fixed by https://github.com/thepeacockproject/Peacock/commit/593792a373f46393fbae32c822bce8ff9e98a11b

**Comment by RDIL** [comment]
Closing as fixed.
