### ISSUE TITLE
PC freeze hard and only the Reset button helps

### ISSUE THREAD

**Issue by Aztec2012** [thepeacockproject/Peacock#140]
When loading a level or playing for 5 minutes with Peacock PC freeze hard and only the Reset button helps.

**Comment by AnthonyFuller** [comment]
Try playing on official, do you experience the same issue?

**Comment by Aztec2012** [comment]
> Try playing on official, do you experience the same issue?

Oh yes in official the same when map loaded. What is this may be?

**Comment by RDIL** [comment]
In that case, it's not a Peacock issue, which is not something we can help with.
