### ISSUE TITLE
Freelancer Mastery not showing properly

### ISSUE THREAD

**Issue by AnthonyFuller** [thepeacockproject/Peacock#170]
When on the "destination" page for Freelancer, when you hover over the Safehouse mission, your current mastery should show on the bottom right (unless you've hit max level of course). This works on official, but not on Peacock.

Official:
![image](https://user-images.githubusercontent.com/24512050/229243206-8400f922-a9ce-4838-917e-bf3bb89610c7.png)

Peacock:
![image](https://user-images.githubusercontent.com/24512050/229243333-428c5be4-1f0f-4bd2-ab26-62c3d00fdcdb.png)

**Comment by AnthonyFuller** [comment]
Oh and, the background is broken.

**Comment by LennardF1989** [comment]
I can't replicate the broken background in my Peacock:
![image](https://user-images.githubusercontent.com/869973/229247689-7add6358-cc61-4431-a458-9c5af5e559c4.png)

**Comment by AnthonyFuller** [comment]
That could be a product of Heritage UI, I'll investigate later.
