### ISSUE TITLE
Gather system/game information and log it on startup for better support

### ISSUE THREAD

**Issue by LennardF1989** [thepeacockproject/Peacock#181]
Now that we have log files, it would be nice to gather some basic information on startup and log that. This way the user will only have to share a log file to provide us with all the info we need to figure out an issue.

Currently Dyno will ask for the following:
- OS (for example Windows 10): 
- Game and Version (for example Hitman WoA 3.140.0 from Epic Games): 
- Peacock version (displayed under the ASCII art banner): 
- Installed plugins and mods, if any:
- The latest server logs file under the logs folder (close Peacock first):
- Other information (for example the patcher logs):

Depending on some situations, we can figure out most of this before the first request, and some after the first request.

**Comment by RDIL** [comment]
Closing because we have export debug info.
