### ISSUE TITLE
Support unhandled URLs

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#182]
- [ ] `/resources-8-11/menusystem/elements/settings/language/items/subtitlebgalpha.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/playeraid/items/walkspeedtoggle.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/playeraid/items/instincttoggle.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/playeraid/items/precisionaimtoggle.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/playeraid/items/itemplacementtoggle.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/reflex.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/dlssg.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/ssaamethod.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/ssaaquality.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/rt_enable.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/rt_reflectionquality.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/rt_shadowquality.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/settings/graphics/items/atmosphericquality.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/mastery/data/issinglehugemasterydata.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/actions/availability/data/missingentitlement_storeurl.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/pages/planning/data/data_contextbutton_reset.json?sv=2018-03-28&ver=h3`
- [ ] `/resources-8-11/menusystem/elements/mastery/masterylocationtabasync.json?sv=2018-03-28&ver=h3`
- [x] `/resources-8-11/menusystem/pages/hub/dashboard/dashboard_live.json?sv=2018-03-28&ver=h3`

According to [the logs shared here](https://discord.com/channels/826809653181808651/1077036810082979974/1092879344327737447) there are a lot of unhandled URLs, mostly concerned with settings. Even though they are likely unrelated to the bug that the op was experiencing, we should try to support them.

**Comment by moonysolari** [comment]
Excluding `/resources-8-11/menusystem/pages/hub/dashboard/dashboard_live.json?sv=2018-03-28&ver=h3` because yes

**Comment by RDIL** [comment]
Where are all these used?

**Comment by moonysolari** [comment]
Settings, I guess, but I don't have much of a clue either.

**Comment by AnthonyFuller** [comment]
I have no idea why the game is requesting some of these, they are in the game files. I've also not seen many of these requested, care to share how you got them to show?

**Comment by moonysolari** [comment]
They are from a log file that a user posted in discord, the link to which was included at the top of this thread.

**Comment by AnthonyFuller** [comment]
The rest of these are retrieved from the files, no idea why they are being requested, everything works fine with them.

Closing as won't fix.
