### ISSUE TITLE
Tightening the Screw auto-completes

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#188]
Tightening the Screw (a plumber pack challenge in Sapienza in H2) automatically completes even if I have never completed it.

**Comment by AnthonyFuller** [comment]
What's the ID of the challenge?

**Comment by moonysolari** [comment]
`e14309fe-2899-4fe4-bf65-dc5c6c599ff5`

**Comment by AnthonyFuller** [comment]
Looks like the SMP might be having some issues on that challenge, it'll need to be debugged.

**Comment by moonysolari** [comment]
Found the culprit. `eq` does not support arrays with more than two items.
``` json
{
    "Condition": {
        "$eq": [
            "$.CountRed",
            "$.CountGreen",
            "$.GoalGreen",
            "$.GoalRed"
        ]
    },
    "Transition": "Success"
}
```
