### ISSUE TITLE
Going to undiscovered map areas in Freelancer mode breaks that map's "Discover [location]" challenge

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#193]
If you start a freelancer contract in a map where you have an undiscovered area, to which you then go to, you will "discover" it and the pin on the map will be replaced by the name of that area. However, this will not cause the "Discover [location]" challenge of the map to register that you have discovered that area, because this challenge is not present for Freelancer missions. This challenge will not be able to be completed, as a result. Currently the only way to resolve this is to do a full reset on all map area discoveries across all maps.

The game requests area discovery progress from the server with an `/authentication/api/userchannel/ProfileService/GetProfile` request, and the discovery progress is in `extensions.gamepersistentdata` in the response. It updates the discovery progress on the server with a  `/authentication/api/userchannel/GamePersistentDataService/SaveData` request. Neither request bears any information about the type of the contract. So we cannot try to cheat the game into thinking that the map is fully discovered only during Freelancer gameplay. 

Official has the same behavior. Currently the only solution I have for this problem is to ignore the `/SaveData` request, and update the area discovery progress when receiving an `AreaDiscovered` event via 
`SaveEvents2` instead. This is because the request of `SaveEvents2` comes with the contract session Id, which can be used to tell whether a session is an evergreen session. Area discovery progress is only saved when the session is not an evergreen session.

**Comment by LennardF1989** [comment]
I have logs going back to the playtest of freelancer so I can check what it did with the discovered challenges.

**Comment by moonysolari** [comment]
> I have logs going back to the playtest of freelancer so I can check what it did with the discovered challenges, since you had a clean profile there.

Did it have fully discovered maps or undiscovered ones?

**Comment by LennardF1989** [comment]
My logs are full of "AreaDiscovered" events:
```{"userId":"8f9d664e-2292-4067-a9fd-417ec330b117","values":[{"Timestamp":524.111389,"Name":"AreaDiscovered","ContractSessionId":"2517347336988548889-7f2368b6-9dfc-405e-826f-34505b2ca859","ContractId":"4a34f12a-ab98-4dc5-9262-c600193b2629","Value":{"RepositoryId":"c6fbd15b-6b6e-4bf0-947d-a3d0a3509e93"},"UserId":"8f9d664e-2292-4067-a9fd-417ec330b117","SessionId":"76561197989140534-1442036064","Origin":"gameclient","Id":"d52109a4-fba1-420e-ae2d-7e28d1161ff8"}]}```

So it's safe to say that Freelancer doesn't have all locations discovered.

**Comment by AnthonyFuller** [comment]
They don't have all locations discovered.

**Comment by moonysolari** [comment]
It might be possible to always add the `repoIds` of the areas to the challenges every time SaveData is received..

**Comment by AnthonyFuller** [comment]
That would require having some sort of list of what area IDs link to what discovery challenge.

**Comment by moonysolari** [comment]
> That would require having some sort of list of what area IDs link to what discovery challenge.

Exactly, and it would be painful to acquire this list, which is why I proposed the solution to ignore `SaveData` requests and only save at `AreaDiscovered` events.

**Comment by AnthonyFuller** [comment]
So we update the challenge progress on receipt of the `AreaDiscovered` event? That seems a bit painful to do also.

**Comment by moonysolari** [comment]
> So we update the challenge progress on receipt of the `AreaDiscovered` event? That seems a bit painful to do also.

Admittedly, but way better than sorting out 700 or so `PersistentBool`s.
