### ISSUE TITLE
Add a flag to toggle whether default starting suits are automatically awarded to the player

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#200]
We should add a flag to toggle whether normal starting suits are added to the inventory and it should be defaulted to false, because:
- Too many "Subject 47 suit not working" questions received.
- Some of them are rewards (Tactical Turtleneck, wetsuit), awarding them directly defeats the purpose.
- They clog up the inventory, especially when the gloved/hatted variants are also present.

Note that when they are not in the inventory, it must still be possible to choose them in their respective locations.

**Comment by ZedKGaming** [comment]
With the Career Progression coming with the next update, this is probably coming too.
