### ISSUE TITLE
"Defeat 10 [crime type] syndicates" challenges not working

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#207]
These challenges are listening for a `MissionCompleted_Event` event. Before the event, the context was
```
 {"Count":0,"CrimeType":2,"ValidLocation":true}  
```
After the event, the context became
```
{"Value":"","Count":0,"CrimeType":2,"ValidLocation":true}
```
which indicates that a bug occurred when handling that event for these challenges.

**Comment by AnthonyFuller** [comment]
I have tried and could not re-create this, further investigation required. Deferring to v6.3.

**Comment by moonysolari** [comment]
This was caused by using an outdated version of the SMP locally. Updating the SMP solved the problem.
