### ISSUE TITLE
Bugs for when mastery progression is disabled

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#221]
- It does not unlock loadout slots in Hokkaido and Miami. Originally reported in [the Discord](https://discord.com/channels/826809653181808651/1097215385390039050).
- It still shows the mastery and challenge rewards on the mission end screen.

**Comment by AnthonyFuller** [comment]
Should flipping the mastery flag set all levels to their max?

**Comment by moonysolari** [comment]
I don't think it currently does, but rather it gives all unlockables. Then again I'm not very familiar with the progression system.

**Comment by AnthonyFuller** [comment]
> It still shows the mastery and challenge rewards on the mission end screen.

I don't see this as a bug. This allows users to complete challenges as well.

> It does not unlock loadout slots in Hokkaido and Miami.

This is a bug.
