### ISSUE TITLE
The description of Big Brother in The McVeigh Ascension does not match the requirements

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#232]
The Big Brother gamechanger in The McVeigh Ascension level 3 only adds the cameras but does not require the player to erase the data in 2 minutes. However, the description in-game says that the player has to erase the data in 2 minutes.

**Comment by AnthonyFuller** [comment]
It should as it's an official gamechanger. Either way, not a Peacock bug.
