### ISSUE TITLE
Broken challenges

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#252]
- [x] [Mirror Mirror](https://discord.com/channels/826809653181808651/1099992627992084551)
- [x] [Elusives challenges](https://discord.com/channels/826809653181808651/1097149979698663544)
- [x] [Been There Done That](https://discord.com/channels/826809653181808651/1100050657387479161): The server only gets a `DeterministicMode` event at the beginning of the first level, but the state of the SMP isn't saved. So in lvl 1 the SMP will get `DeterministicMode` and will transit to `CheckCompletion`, but when lvl 2 starts, the SMP is restarted, so it forgets that this challenge was previously at `CheckCompletion`.
- [x] The Scenic Route
- [ ] Getting your hands dirty
- [x] The silent assassin challenge for sniper `029c4971-0ddd-47ab-a568-17b007eec04e` does not get to `Success` because weirdly the `ContractEnd` event isn't actually reached in the statemachine.

All of these broken challenges are probably all timer-related, and fixing one might fix all of them:
- [x] [In Plain Sight](https://discord.com/channels/826809653181808651/1093586330707046430)
- [x] [Safe Room Explosion](https://discord.com/channels/826809653181808651/1102591331647369266)
- [ ] [Oh Deer](https://discord.com/channels/826809653181808651/1102565230631997451)
- [x] Bullet Points
- [x] Big Bada Boom

**Comment by AnthonyFuller** [comment]
> The server never got a `DeterministicMode` event.

It may be something like the `ChallengeCompleted` event where the server sends it. We can just check the entrance on the first contract and start it. I'll look into how official does it.

**Comment by AnthonyFuller** [comment]
I'm not even going to test Oh Deer, because I hate that challenge so much. Since timers now work immaculately for Sniper, this should also be fixed.

Getting Your Hands Dirty was another timer issue.
