### ISSUE TITLE
The "Mission Failed" menu for elusive targets only has the "Exit to Menu" option

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#253]
![image](https://user-images.githubusercontent.com/118079569/234489422-3a441fe2-02c0-403d-9673-69dc4f0fedb0.png)

**Comment by AnthonyFuller** [comment]
This can only be fixed with a clientside mod, it has been added to [peacock strings](https://github.com/thepeacockproject/peacock-strings)

**Comment by AnthonyFuller** [comment]
I lied.
