### ISSUE TITLE
Hitman 2 Standard access pass incorrectly grants some Hitman 2 Expansion items in Hitman 3

### ISSUE THREAD

**Issue by thecnoNSMB** [thepeacockproject/Peacock#289]
**Describe the bug**
As in title; specifically, a base Hitman WOA install on Peacock with the Hitman 2 Standard access pass grants the [Collector's Pack](https://hitman.fandom.com/wiki/Collector%27s_Pack) and [Smart Casual Pack](https://hitman.fandom.com/wiki/Smart_Casual_Pack) items, which are [intended to be exclusive to the Hitman 2 Expansion](https://store.steampowered.com/bundle/30335/HITMAN_World_of_Assassination_Deluxe_Pack/). In addition, the game allows you to start a mission with the erroneously granted items and make game saves with them, but it _will not_ allow you to load the resulting saves, because you obviously do not have the expansion.

**To reproduce**
Clear user progression on a Peacock server, and start Hitman 3 without owning Hitman 3 Access Pass: Hitman 2 Expansion. Disabling/uninstalling the expansion through Steam might also work.

**Comment by AnthonyFuller** [comment]
I've noticed issues with entitlements too, the WoA update messed it all up. Will be fixed in v7.

**Comment by AnthonyFuller** [comment]
@thecnoNSMB Was this on Steam or Epic?

**Comment by thecnoNSMB** [comment]
@AnthonyFuller This was on Steam. Apologies for the delay, I haven't checked my Github notifications in a while.
