### ISSUE TITLE
Impossible complete escalation on five stars

### ISSUE THREAD

**Issue by Dinozafre** [thepeacockproject/Peacock#290]
**Description**
If escalation have some complication, even when this just restricted loadout.

**How to get this issue**
Complete escalation with some complication, and get four stars in scoring screen
Edit: i fix the issue

**Comment by AnthonyFuller** [comment]
You edited saying you fixed the issue, what was it?

**Comment by Dinozafre** [comment]
Just i ned restart the peacock server, and now all okay
