### ISSUE TITLE
Hitman 1 Professional Mode Support

### ISSUE THREAD

**Issue by athu16** [thepeacockproject/Peacock#296]
Are there plans to add Mastery support for HITMAN 1's Professional mode? Right now all the professional mode mastery rewards (the best weapons) are unlocked right from the start, and in the stats screen the mastery rewards are identical for normal and professional modes.

**If not, is there a way to "disable" items so they don't show up in-game?**

**Comment by RDIL** [comment]
Yes! We hope to support this feature sometime in the near future hopefully.
