### ISSUE TITLE
Planning for limited-loadout locations is broken on v7

### ISSUE THREAD

**Issue by jorys-paulin** [thepeacockproject/Peacock#298]
**Describe the bug**
When you try to access the planning page for missions taking place in Hokkaido or Miami, where you can't bring any items with you until you get to a mimimum mastery level, the server just errors out:
```
[11:06:47:884] [Debug | planningView] Looking up details for contract - Location:LOCATION_MIAMI (assembly:/_pro/scenes/missions/miami/scene_flamingo.entity)
[11:06:47:886] [Error | uncaught] Cannot read properties of undefined (reading 'size')
[11:06:47:886] [Error | uncaught] TypeError: Cannot read properties of undefined (reading 'size')
    at getUnlockableById (c:\Laragon\www\Peacock\components\inventory.ts:412:29)
    at planningView (c:\Laragon\www\Peacock\components\menus\planning.ts:381:35)
```

Here's my [DEBUG_PROFILE.zip](https://github.com/thepeacockproject/Peacock/files/12061093/DEBUG_PROFILE.zip) with the complete logs.

**To reproduce**
You can run Peacock from source using the latest commit from the `v7` branch. You can start any mission set in Hokkaido or Miami from the destinations or campains tab in the main hub.

**Additional context**
The code at fault inverted the parameters sent to the `getUnlockableById`. It expects an `id` and a `gameVersion` but the call from `components/menus/planning.ts` inverted the two, sending `gameVersion` first and then `id`: `{ id: 'h3', gameVersion: 'LOADOUT_UNLOCK_MIAMI' }`

What's weirder is that this code hasn't been touched since it was added, meaning this code never worked. And yet there's no problem in the Peacock release `v6.4.0`, even though the commit it belongs to has the bug:
```
const loadoutUnlockable = getUnlockableById(
    req.gameVersion,
    req.gameVersion === "h1"
        ? sublocation?.Properties?.NormalLoadoutUnlock[
              contractData.Metadata.Difficulty ?? "normal"
          ]
        : sublocation?.Properties?.NormalLoadoutUnlock,
)
```

This code should be included in all releases since `v6.1.0`, yet none of them have the issue, why doesn't the bug appear there? Unless the code is being patched, but the releases are built by CI it seems, and there's nothing there?

I feel like the solution is right under my nose and I'm just dumb, but I have a pull request ready to go that un-inverts the arguments sent to the function.

For reference, here's the link to the Discord thread in which I first reported the issue : https://discord.com/channels/826809653181808651/1129701652279070750

**Comment by jorys-paulin** [comment]
For future reference, it was the function itself that was refactored in 580caea. Everything calling that function was updated except for `components/menus/planning.ts`.
That commit also happened after the release of `v6.4.0`, which is why the bug isn't in any of the released versions so far.

**Comment by RDIL** [comment]
> Unless the code is being patched, but the releases are built by CI it seems, and there's nothing there?

Yeah, all the releases are downloaded from the CI and uploaded to the GitHub release. Should be identical on both ends.
