### ISSUE TITLE
Disable quick menuing for Freelancer

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#300]
**What**
We need to add a toggle that disables the special one-click join Freelancer title on the main menu

**Why**
It's apparently an unfair advantage for speedruns, and this is needed to prevent Peacock from being removed from the approved tools list for Freelancer.

**Comment by AnthonyFuller** [comment]
What?! This is absolutely absurd.

**Comment by Cookie303728** [comment]
Why does it make a difference vs just navigating to the freelancer menu

**Comment by RDIL** [comment]
Closing due to F key working
