### ISSUE TITLE
Sniper scoring challenge multiplier always maxed out

### ISSUE THREAD

**Issue by alex47exe** [thepeacockproject/Peacock#305]
**Describe the bug**
Not sure if this is a bug or if it's intended to be that way, but sniper scoring challenge multiplier is always maxed out (3.0 for Siberia) when 'enableMasteryProgression = false' in 'options.ini', instead of the one showing at the end - 1.04, 1.09, etc, depending on how many challenges have been completed. It only works properly when using 'enableMasteryProgression = true' and using a different method to have all items unlocked.

**To reproduce**
I've used the latest compiled mv-mastery build with 'enableMasteryProgression = false' in 'options.ini'.

**Comment by AnthonyFuller** [comment]
With the way mastery progression works, that's intentional, it gives you **all** unlocks from challenges and mastery. A better name for it is `enableProgression`. Probably will change the option name for v7.
