### ISSUE TITLE
When service is running from WebStorm  cant  success in  auth inside the game.  

### ISSUE THREAD

**Issue by Postal86** [thepeacockproject/Peacock#325]
Seems  cant connect to Peacock local  service. 

![image](https://github.com/thepeacockproject/Peacock/assets/15318234/cec73f2a-da58-4f2f-952c-ab8ecbeb0a60)

I uploaded the print screen of an issue.  

Thnks.

**Comment by RDIL** [comment]
Can you show the server logs?

**Comment by Postal86** [comment]
> Can you show the server logs?

Hello. Sorry  not familiar with  source code at the moment  can u  hint  me where logs are located ? :) ;)

**Comment by Postal86** [comment]
![image](https://github.com/thepeacockproject/Peacock/assets/15318234/392b551a-2893-437f-9f1b-d90c5b591a08)

**Comment by RDIL** [comment]
What platform are you on, steam or epic? and which DLC do you own?

**Comment by Postal86** [comment]
Ouch to be honest  not a bought game.  downloaded from torrent .

**Comment by Postal86** [comment]
Game version is 3.160 and also  game has itself  Peacock server  v6.5.2 (rev  6520).   And  that peacock  is working  but when i am cloning  same version from github  and  debuging from Webstorm also patching as required during connection with Peacock  is  failing am i missing something ?!

**Comment by grappigegovert** [comment]
Peacock only works with purchased steam or epic versions of the game, as listed on the website: https://thepeacockproject.org/wiki/intel/requirements
The version that you downloaded from some other website most likely is a modified version of Peacock not supported by us.

**Comment by AnthonyFuller** [comment]
Either way, we don't support people with pirated copies. At least you had some initiative to go to GitHub.
