### ISSUE TITLE
Items not normally stashable can be equipped

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#333]
**Describe the bug**
Seems certain items like muffins/crowbars can be stashed in small smuggle points, while the official servers do not allow this.

**To reproduce**
https://www.youtube.com/watch?v=53EuzPE56G0
Official servers don't allow bringing muffins to that stashpoint

**Additional context**

**Comment by grappigegovert** [comment]
I think we might need to check the `ItemSize` property in the repository for this.
