### ISSUE TITLE
DLC absent

### ISSUE THREAD

**Issue by Meyson7T** [thepeacockproject/Peacock#336]
(via google translate) hello I have a problem with my peacock in relation to the additional content, when I launch hitman with peacock in the game, the entire map ambrose and certain packs like the 7 deadly sins or the street dlc in freelancer mode are not present even though they are present on the ioi server? this has happened since the recent hitman update

**Comment by Meyson7T** [comment]
However, I installed the latest version of peacock, I forgot to specify it

**Comment by RDIL** [comment]
Going to close this, we made a lot of changes to improve how this is handled. Please let us know if it's still an issue on the latest version.
