### ISSUE TITLE
ETA menu does not work on v7

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#351]
It works on v6 (including the new custom ETA) but not on v7. Can anyone reproduce?

![image](https://github.com/thepeacockproject/Peacock/assets/118079569/a40fe5ea-582f-4cd3-b4e1-4165fe3024a4)

**Comment by AnthonyFuller** [comment]
Works fine on v7 for me.

**Comment by moonysolari** [comment]
Closing this for now because I have diffed the response given by v6 and v7 and they seem to be identical. However I am still experiencing this issue on v7. Open later if reproduced by anyone else.

**Comment by RDIL** [comment]
Reopened as it just happened to me while working on my rdil/routing branch
