### ISSUE TITLE
Proper killing conditions absent from displayed objective tips in certain peacock escalations

### ISSUE THREAD

**Issue by suanjiansalt** [thepeacockproject/Peacock#353]
**Describe the bug**
I've found that some peacock escalations have incorrect in-mission display texts that lack of killing conditions. For example:

- _The Christmas Calamity_ (southern comfort) : It says "Eliminate targets" but in this escalation you can just pacify them. Plus, this escalation is unique to lack of exclusive images, both for title and objectives.
- _The dez Dichotomy_ (rosebush) : Lack of disguise conditions (mansion staffs / guards). Plus, in Level 3 we need to eliminate the two Jay Harrises.
- _The mendietinha Madness_ (shangrila) : Lack of disguise condition (delivery man) + killing methods (Bartoli Woodsman Sniper Rifle, explosive accident).
-  _The Yannini Yearning_ (yannini) : Lack of killing methods (pistol).

I wanted to fix it myself, but struggled to find a way to perfect it. Mainly I don't even know exactly where to change.

**Comment by suanjiansalt** [comment]
So finally I decide to dig into it...
The "BriefingName"&"BriefingText" lines are for sentences in planning section, and the "HUDTemplate" is for in-mission display sentence. The "ObjectiveType" determines icon before the text. All I need to do is replace "$loc localizations", right?
If I know that I would be able to start.

**Comment by grappigegovert** [comment]
Only use iconType for the icon, ObjectiveType changes the way it's displayed in the planning page (see this function: https://github.com/thepeacockproject/Peacock/blob/v7/components/contracts/dataGen.ts#L354)
You can use `$($repository npc-repository-id-here).Name` to get an NPC's name, often used like this:
```json
"HUDTemplate": {
	"display": {
		"$loc": {
			"data": "$($repository f03a4c5a-767f-4315-a160-baef4bd1def0).Name",
			"key": "UI_CONTRACT_GENERAL_OBJ_KILL"
		}
	}
}
```
This uses the localization key "UI_CONTRACT_GENERAL_OBJ_KILL", which in english is "Kill {0}", and replaces the {0} with the NPC's name.

**Comment by suanjiansalt** [comment]
> You can use `$($repository npc-repository-id-here).Name` to get an NPC's name, often used like this:
> 
> ```json
> "HUDTemplate": {
> 	"display": {
> 		"$loc": {
> 			"data": "$($repository f03a4c5a-767f-4315-a160-baef4bd1def0).Name",
> 			"key": "UI_CONTRACT_GENERAL_OBJ_KILL"
> 		}
> 	}
> }
> ```
> 
> This uses the localization key "UI_CONTRACT_GENERAL_OBJ_KILL", which in english is "Kill {0}" (i think), and replaces the {0} with the NPC's name.

Thank you, but I didn't mean that... I meant how to get NPCs' names with their "Id"s listed in the `contractdata` folder, like, in this code block:

> ```json
> "_comment": "security2",
> "Type": "statemachine",
> "Id": "bca06014-1580-4837-916a-95bc9f64d76a",
> "BriefingText": {
>        "$loc": {
>               "key": "UI_CONTRACT_GENERAL_OBJ_KILL",
>               "data": "$($repository 1639e08a-4150-4a92-a4b3-bcec99b336fe).Name"
>        }
> },
> "HUDTemplate": {
>         "display": {
>                "$loc": {
>                       "key": "UI_CONTRACT_GENERAL_OBJ_KILL",
>                        "data": "$($repository 1639e08a-4150-4a92-a4b3-bcec99b336fe).Name"
>                }
>         }
> },
> ```

How to transmit `bca06014-1580-4837-916a-95bc9f64d76a` into a name out of game and out of server (for example using a tool like RPKG Tool)? And why is "Id" different from id in `"data": "$($repository npc-repository-id.Name)`?

And of course I'm not aware of ways to turn NPC name to repository Id neither... 😭

**Comment by grappigegovert** [comment]
The first `Id` in that block is the Id of the objective, and is unrelated to the target NPC. The objective Id is just a random Id that needs to be different for each objective, but doesn't affect anything else.

The id `1639e08a-4150-4a92-a4b3-bcec99b336fe` is the id of the target NPC and you can look those up in the repository, for example with RPKG Tool in the 'REPO' tab.
![image](https://github.com/thepeacockproject/Peacock/assets/1353729/5feef818-addc-4030-bd10-fcb4839c7d4a)
