### ISSUE TITLE
Unwanted handler's voice appearing when killing main story targets in peacock escalations

### ISSUE THREAD

**Issue by suanjiansalt** [thepeacockproject/Peacock#371]
**Describe the bug**
Including but not limited to _The CurryMaker Chaos_, and _The Christmas Calamity_.

**Comment by moonysolari** [comment]
I can reproduce this on The CurryMaker Chaos but not on The Christmas Calamity.

**Comment by suanjiansalt** [comment]
> I can reproduce this on The CurryMaker Chaos but not on The Christmas Calamity.

How could be that, did you eliminate Gonif or Bagnato with xmas items? I re-downloaded one peacock copy and tested, where eliminating both Gonif and Bagnato will trigger "Ho Ho Ho" dialogue either.

**Comment by RDIL** [comment]
That's just part of the scene file.

**Comment by suanjiansalt** [comment]
> That's just part of the scene file.

It's uneditable, right?

**Comment by moonysolari** [comment]
For The CurryMaker Chaos there exists a Hokkaido scene file without the "target down" voice lines, so I used that one and it is now fixed, but there does not seem to be one for HH, so I'd imagine it to be a client-side edit.

**Comment by AnthonyFuller** [comment]
There should be one for HH. It has contracts now.

**Comment by moonysolari** [comment]
HH contracts on official have the handler voice lines too, so I don't think they made a new one.
