### ISSUE TITLE
Seasonal Events (HH & HSF) haven't got separated with main missions in Location page

### ISSUE THREAD

**Issue by suanjiansalt** [thepeacockproject/Peacock#372]
**Describe the bug**
Which was changed after official Oct 2023 patch.

**Comment by moonysolari** [comment]
Good catch. I might fix it together with the challenge packs.

**Comment by moonysolari** [comment]
Wait, what does the "Location page" here refer to?

**Comment by suanjiansalt** [comment]
> Wait, what does the "Location page" here refer to?

Destination > Paris, containing The Showstopper, The Director, Holiday Hoarders and a bunch of escalations.

Destination > Hokkaido, containing Situs Inversus, The Controller, Hokkaido Snow Festival and a bunch of escalations.

**Comment by moonysolari** [comment]
I don't see where the difference is between Peacock and official on this matter...

**Comment by suanjiansalt** [comment]
Are your two missions separate from The Showstopper and Situs Inversus + Patient Zero respectively? If yes - I guess you can just close this issue now.

However both this issue and issue No. 371 are tested by me in a independent copy of peacock... Anyway, I've said enough.

**Comment by moonysolari** [comment]
![1706264667599](https://github.com/thepeacockproject/Peacock/assets/118079569/bc95c98d-77bc-4cda-bd06-bf98cbe14277)
![1706264704264](https://github.com/thepeacockproject/Peacock/assets/118079569/b0ff55a4-7d37-4ad0-b0fb-5560c4a1a824)
Is this the behavior you are looking for? If not please attach screenshots of the issue.

**Comment by moonysolari** [comment]
Also, for #371 I tried again and successfully reproduced it. However there does not seem to exist an easy solution to remove the HH handler voice, at least on the server side.

**Comment by suanjiansalt** [comment]
> Is this the behavior you are looking for? If not please attach screenshots of the issue.

That's what the ideal state would look like, but that's not what it shows in my device here:

![屏幕截图 2024-01-26 183655](https://github.com/thepeacockproject/Peacock/assets/127009844/361f70cc-cbef-4b20-9e62-2b91e38a3c90)
![屏幕截图 2024-01-26 183715](https://github.com/thepeacockproject/Peacock/assets/127009844/885e6b92-b73e-41b0-8d56-e901f6f92cc1)

**Comment by moonysolari** [comment]
Which version are you on?

**Comment by suanjiansalt** [comment]
![屏幕截图 2024-01-26 191804](https://github.com/thepeacockproject/Peacock/assets/127009844/1951b56d-3308-433e-993b-1f0c8458e353)

**Comment by moonysolari** [comment]
I was using latest v7 so I think the issue has already been resolved.
