### ISSUE TITLE
Escalation tile doesn't work as official

### ISSUE THREAD

**Issue by suanjiansalt** [thepeacockproject/Peacock#376]
**Describe the bug**
Now in escalation tile in the main page we can display Peacock exclusive escalation contracts of which we are proud. However, unlike official server behavior, we just permanently show around 4 or 5 of them, like jeffery, purplekey blah blah, which means when you complete one series of escalation it's still on the tile, only to attach a check mark (√) to it.

**Comment by RDIL** [comment]
Works as intended - we want to showcase Peacock escalations. This is replaced with a static tile in v7.

**Comment by suanjiansalt** [comment]
I mean - shouldn't it disappear after we complete an escalation?

**Comment by AnthonyFuller** [comment]
Well no, because the point of it is just show X amount of "featured" escalations. As said by @RDIL, this issue is redundant as it has been changed.
