### ISSUE TITLE
I dont have every item in the game

### ISSUE THREAD

**Issue by billiam111206** [thepeacockproject/Peacock#378]
I load the game and I do not have every item. I don't even have half of every item. I had every item yesterday when I used this so I don't know the problem.

**Comment by moonysolari** [comment]
v6.1.0 introduced mastery progression, it is enabled by default. To disable it and unlock all items, set `enableMasteryProgression` in `options.ini` to `false`, and restart Peacock. For more info on how to edit the `options.ini` file and general info about how to use Peacock, check here:  https://thepeacockproject.org/wiki/intel/what-is-peacock#how-does-peacock-work
