### ISSUE TITLE
Cannot enter planning page of contracts whose JSONs are not found locally

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#382]
e.g. Trending, most played last week, and contract search. Broken by #362.

**Comment by RDIL** [comment]
I'm thinking that if we fetch something from the official servers, we should save it. I'd consider this intended behavior, as we shouldn't try and fetch everything on every single route.

**Comment by moonysolari** [comment]
Around 10-20 contract JSONs are fetched when the respective contract menus are loaded, and the user will only play a few of them as they browse through the menus. It's a bit wasteful to save all contract JSONs fetched when most of them will not be played.

**Comment by RDIL** [comment]
IOI does not want us making mass requests to their servers - if we're going to fetch something, we need to not re-fetch it unless absolutely needed.

**Comment by grappigegovert** [comment]
> Around 10-20 contract JSONs are fetched when the respective contract menus are loaded, and the user will only play a few of them as they browse through the menus. It's a bit wasteful to save all contract JSONs fetched when most of them will not be played.

Contract jsons are only about 10KiB each (pretty printed, so even less minimized), so even storing hundreds of them will only take up a couble of megs
