### ISSUE TITLE
doesnt even give me everything

### ISSUE THREAD

**Issue by Sailolbody** [thepeacockproject/Peacock#387]
so i just installed the peacock project and it does work, but when to my stuff i still have black and chrome silverballers and still have the same stuff
i also made sure the patcher said peacock local and it said powered by peacock

**Comment by suanjiansalt** [comment]
v6.1.0 introduced mastery progression, it is enabled by default. To disable it and unlock all items, set enableMasteryProgression in options.ini to false, and restart Peacock. For more info on how to edit the options.ini file and general info about how to use Peacock, check here: https://thepeacockproject.org/wiki/intel/what-is-peacock#how-does-peacock-work
