### ISSUE TITLE
Peacock Patcher appears very blurry when using 125% scaling in Windows on a 1080p display

### ISSUE THREAD

**Issue by thecatontheceiling** [thepeacockproject/Peacock#395]
**Describe the bug**
read the title

**To reproduce**
1. Right click on the desktop
2. Click "Display Settings"
3. Set scaling to 125% (default is 100%)
4. Open Peacock Patcher and observe

**Comment by RDIL** [comment]
Hey, thanks for the report! Can you please try out our experimental [core patcher](https://github.com/thepeacockproject/Peacock/actions/runs/7949762866?pr=388) and see if the issue still persists?

**Comment by thecatontheceiling** [comment]
sure thing! do I just need to replace the .exe file and it shouldn't mess with anything else?

**Comment by RDIL** [comment]
Correct

**Comment by thecatontheceiling** [comment]
the updated patcher does not have this issue. crystal clear
![image](https://github.com/thepeacockproject/Peacock/assets/75037904/b2acb74b-fe5f-47c6-8869-038a4cd76b8d)

**Comment by thecatontheceiling** [comment]
why is it 200 mb though? lol
the old patcher isnt even a megabyte

**Comment by RDIL** [comment]
Glad to hear the new patcher fixes the problem! The size concern is absolutely valid though, and it’s something we’re working on minimizing.

**Comment by thecatontheceiling** [comment]
peacock 6.6.0 has the updated patcher and therefore this issue can be closed. thanks.
