### ISSUE TITLE
Level 5 not labeled properly: "The Gemini Fiasco - Escalation Contract" in the "Paris" location

### ISSUE THREAD

**Issue by MisterFloppy** [thepeacockproject/Peacock#403]
I'm playing "Hitman" in german language while using Peacock v7 alpha 7 and have noticed a strange thing regarding "The Gemini Fiasco - Escalation Contract" in the "Paris" location:

After having completed level 5 of it. although properly
- the completion status of this escalation in the menu is checked and
- none of the displayed 5 toxic skull icons is greyed out anymore,

the label of this level still says "Das Gemini Fiasko - Stufe 4"!
"Stufe 4" in german means "Level 4" - correctly it should say "Stufe 5" ("Level 5").

Just to be sure, I've reset and played the escalation again, but nothing has changed. I don't know if it Is misbehaving like this only in the german version.

**Comment by RDIL** [comment]
This is an issue on IOI's end, it's listed as [level 5](https://github.com/thepeacockproject/Peacock/blob/v7/contractdata/PARIS/ESCALATION/ANEMONE/ANEMONE5.json#L255) on our end.

**Comment by AnthonyFuller** [comment]
cc @dribbleondo

**Comment by RDIL** [comment]
Opened issue: https://github.com/glacier-modding/H3-Community-Patches/issues/64

**Comment by dribbleondo** [comment]
Will add to [TGBLR](https://www.nexusmods.com/hitman3/mods/549) and community patches presently
