### ISSUE TITLE
Support challenge packs

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#409]
I have a half-baked implementation on a branch in my fork but I'm not satisfied with it. Also I don't have enough time these days to work on it so if anyone's interested feel free to pick this one up.

**Comment by AnthonyFuller** [comment]
I may be able to squeeze this into v7, and something else I've been wanting to do.

**Comment by AnthonyFuller** [comment]
Done!

**Comment by moonysolari** [comment]
Thanks, that was fast
