### ISSUE TITLE
Unwarranted "sambuca3 start" challenge in Hitman 2

### ISSUE THREAD

**Issue by suanjiansalt** [thepeacockproject/Peacock#413]
![image](https://github.com/thepeacockproject/Peacock/assets/127009844/0009b72b-980a-465f-89f8-d3ff40c433ca)

Should be linked to the shared challenge settings between H2 and H3.

For H2, it should be "Blind All Humans".

**Comment by AnthonyFuller** [comment]
I checked and it wasn't there! (I might've checked The Undying).

**Comment by AnthonyFuller** [comment]
Fixed in [042af36](https://github.com/thepeacockproject/Peacock/commit/042af36d04547e7477d6ba39796a2570e97b2e04)
