### ISSUE TITLE
None of the argentum challenges are working except for the first one

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#415]
They all depend on the completion of another challenge in another location. However when that challenge gets completed, the state of the dependent challenge does not change. This is because the states of a challenge is not tracked when a contract is started that is not in their location.

**Comment by AnthonyFuller** [comment]
Unsupported route is causing this: `/authentication/api/userchannel/ChallengesService/GetProgression`.

**Comment by RDIL** [comment]
we have it for 2016, but apparently it's not legacy code, it's actually used in new game versions!

**Comment by AnthonyFuller** [comment]
Fixed in 28b6673. We'll do a release when Cheesecake is finished.
