### ISSUE TITLE
Sniper Assassin locations on Destinations menu

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#425]
Requested by Kevin

https://discord.com/channels/826809653181808651/1019693314838106173

We should show the 3 sniper locations on the destinations menu.

**Comment by AnthonyFuller** [comment]
No, this could break multiplayer.

**Comment by AnthonyFuller** [comment]
Wouldn't show the Singleplayer/Multiplayer selection screen if available.
