### ISSUE TITLE
Image of "KAI malfunction" information is blank

### ISSUE THREAD

**Issue by MisterFloppy** [thepeacockproject/Peacock#443]
In "HOKKAIDO"'s mission "Situs Inversus" I noticed that the image of "KAI malfunction" information is blank - see below.

Here's an easy way to get to this point:

- start the mission from 47's suite as Tobias Rieper
- use the map to go to the gardens top right corner to find an electrical box
- use it to turn off the bridges lights
- hide in a bush nearby
- wait a while for the hospital director to appear in the garden, he will try to fix the electrical box by himself
- subdue him from behind and take his disguise
- enter the hospital through the closest door just a few steps downwards on the left side
- walk the long corridor all the way up until its end
- enter the room through the door on the right side
- now you have to wait in patience: 3 scientists will have some very, very long conversations with the female one reentering the room multiple times
- finally, she will start to talk about KAIs malfunction, and there will be a message "Information" popping up on the screen
- press "SELECT" on your gamepad (or the corresponding button when you're playing with a keyboard) to reveal the new gained information in detail

![kai-malfunc-err](https://github.com/thepeacockproject/Peacock/assets/6067839/5286674f-35c0-4771-9999-35b9316855e0)

**Comment by suanjiansalt** [comment]
I think this isn't a Peacock bug since I can recurrent this problem in official server.

**Comment by Watchman3001** [comment]
If it is official bug, you can try reporting it to "community patch project" on Glacier Modding Discord, those fellows might fix it

**Comment by RDIL** [comment]
Closing because it's a game bug
