### ISSUE TITLE
Level 5 not labeled properly: "The Gemini Fiasco - Escalation Contract" in the "Paris" location

### ISSUE THREAD

**Issue by MisterFloppy** [thepeacockproject/Peacock#444]
I'm playing "Hitman" in german language while using Peacock v7.2.0 and have noticed a strange thing regarding "The Gemini Fiasco - Escalation Contract" in the "Paris" location:

After having completed level 5 of it. although properly

    the completion status of this escalation in the menu is checked and
    none of the displayed 5 toxic skull icons is greyed out anymore,

the label of this level still says "Das Gemini Fiasko - Stufe 4"!
"Stufe 4" in german means "Level 4" - correctly it should say "Stufe 5" ("Level 5").

Just to be sure, I've reset and played the escalation again, but nothing has changed. I don't know if it Is misbehaving like this only in the german version.

ADDITIONAL NOTE:

I already reported this bug some time ago, and you actually did find a solution, but obviously it did not find its way into Peacock 7.2.0 :-)

Please see here:
[https://github.com/thepeacockproject/Peacock/issues/403](url)

**Comment by RDIL** [comment]
As stated in the previous issue, this isn't a Peacock bug, it's a game bug. In #403 there is a mod linked that is able to fix this, but this isn't a Peacock bug.
