### ISSUE TITLE
The contracts repo cannot be pulled due to invalid filename

### ISSUE THREAD

**Issue by prolium** [thepeacockproject/Peacock#446]
This file has an invalid character which is preventing the repo from being pulled
https://github.com/thepeacockproject/Contracts/blob/main/contracts/h3/%161-20-8070895-27%20XB%3A3-20-9219494-69.json

Error on Windows:
```shell
$ git pull origin
error: invalid path 'contracts/h3/?1-20-8070895-27 XB:3-20-9219494-69.json'
Updating 4f6976da..5536cc93
```

Notice the question mark `?` and colon `:` characters, on Windows these are illegal characters, hence pulling fails

**Comment by RDIL** [comment]
Just deleted. I'll put some extra validation in place to make sure this doesn't happen again.
