### ISSUE TITLE
Freeform Training - Yacht explored challenge

### ISSUE THREAD

**Issue by Watchman3001** [thepeacockproject/Peacock#447]
**Describe the bug**
If playing on peacock after progress transfer, that challenge is softlocked? As all areas are already explored, thus making this challenge impossible to trigger

**To reproduce**
Complete this level on official, have all locations there explored. Transfer data, now you have this challenge hanging there, alone

**Additional context**
Very small issue, but still triggers that perfectionism itch

**Comment by RDIL** [comment]
@nathanchere also reproduced within H2: https://github.com/thepeacockproject/Peacock/issues/456

**Comment by grappigegovert** [comment]
Two more reports of this issue: https://discord.com/channels/826809653181808651/1249470335745786090

**Comment by RDIL** [comment]
If the official servers don’t have this challenge, we should probably just remove it

**Comment by grappigegovert** [comment]
It would be fun if we kept it imo - it shouldn't be too hard to add some special handling for it in the progression handling
