### ISSUE TITLE
"Chameleon" challenge is bugged and resets after save reload/mission restart 

### ISSUE THREAD

**Issue by Watchman3001** [thepeacockproject/Peacock#450]
**Describe the bug**
Pretty much in the title. That challenge in vanilla is cumulative, not requiring you to get all disguises in one sit, that would be a slog on some missions

**To reproduce**
Go to a mission where you don't have that challenge completed, get a disguise, reload a save, try again, and you will see that it got reset to 0

**Additional context**
Tested it a lot on "The Icon" and "Landslide".  Double checked that it is not a mod issue, some tests were run on clear Peacock. Quite a serious issue, hope it can be fixed

**Comment by Watchman3001** [comment]
After some tests and comparisons (thanks to members of Peacock Discord) it might be some strange consequence of progress transfer procedure

**Comment by Watchman3001** [comment]
Another addition - that same bug messes up Sniper Assassin mode. As soon as I kill a bodyguard, and some challenge related to that starts counting, game crashes. Sent Debug to Mr Fuller. Looks like Progress Transfer breaks a lot of challenge related things

**Comment by RDIL** [comment]
Fixed in 8cb7378
