### ISSUE TITLE
Sniper Assassin crash after prog transfer

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#462]
Crashes on the last yardbird (hawk) with a headshot - looks to be the headshot challenge causing it (invalid state due to transfer?) Currently investigating.

Related to #450 
Related to #447

**Comment by RDIL** [comment]
![webstorm64_fxOi01J1Y9](https://github.com/thepeacockproject/Peacock/assets/34555510/3bfd4796-6c70-41ef-baa0-7100365d091d)
Looks like after the transfer, some challenges are missing parts of the state. On the left I have a working profile which hasn't completed the challenge, and on the right, one that crashes.

**Comment by alex73630** [comment]
Fixed in 8cb7378
