### ISSUE TITLE
SA Indicator does not work on custom contract types

### ISSUE THREAD

**Issue by Burn-the-w1tch** [thepeacockproject/Peacock#473]
**Describe the bug**
If setting the type of a contract to a custom value (in my instance 'Roulette') the SA indicator will not work. 

**To reproduce**
Set a contract's type to a non-vanilla value.

**Comment by Burn-the-w1tch** [comment]
Did some further testing, XP bonuses and alerts are not functioning either. (Non-target killed, body hidden, etc)

**Comment by AnthonyFuller** [comment]
Not a bug. You need to alter the inclusion data of global challenges.
