### ISSUE TITLE
Unable to connect in online mode.

### ISSUE THREAD

**Issue by TruantRiccardo** [thepeacockproject/Peacock#487]
I updated the game to version 3.19, and Peacock is up to date. I start the patcher and the server, both of which show no errors, but when I launch the game, after a one-minute attempt, it says it cannot connect.

**Comment by riisikumi** [comment]
Where is your game from?

**Comment by TruantRiccardo** [comment]
You mean the game platform?

**Comment by TruantRiccardo** [comment]
Solved, thanks

**Comment by TruantRiccardo** [comment]
Solved, thanks

**Comment by grappigegovert** [comment]
What did you do to solve the issue?
