### ISSUE TITLE
Achievements pertaining to Lvl 20 Mastery not unlocking.

### ISSUE THREAD

**Issue by talk2g** [thepeacockproject/Peacock#489]
**Describe the bug**
Achievements like 
City of Light
Reach Paris Mastery Level 20.

Etc are not unlocking.
While others like completing a mission are working

**To reproduce**
Reach lvl 20 mastery in Paris 

**Additional context**
On Steam.
Using latest peacock.
Game i own is the part one of hitman woa(s1 only)

**Comment by talk2g** [comment]
Had this happen in both paris and saphienza

**Comment by thecatontheceiling** [comment]
Are you also getting the "constant save" issue? Had a friend try Peacock while owning part one and had the game constantly spam save for some reason

**Comment by Watchman3001** [comment]
> Are you also getting the "constant save" issue? Had a friend try Peacock while owning part one and had the game constantly spam save for some reason

That usually happens if the game version used is not official

**Comment by talk2g** [comment]
> Are you also getting the "constant save" issue? Had a friend try Peacock while owning part one and had the game constantly spam save for some reason

Nope

**Comment by thecatontheceiling** [comment]
> > Are you also getting the "constant save" issue? Had a friend try Peacock while owning part one and had the game constantly spam save for some reason
> 
> That usually happens if the game version used is not official

I know for a fact they did actually own part one, maybe a weird one-off problem then

**Comment by 77HriP77** [comment]
I have the same problem. Got level 20 but the achievement did not open in Steam. Although other achievements for completing story quests opened.

**Comment by Monkein** [comment]
I’m experiencing the same issue. Additionally, I’ve observed a related problem in the Sniper Missions. The achievements for earning 1 million points are also not appearing.
