### ISSUE TITLE
Non-highlighted surgeons

### ISSUE THREAD

**Issue by MamaLuigiToYou** [thepeacockproject/Peacock#499]
**Describe the bug**
In the game, if you have "elusivesAreShown" set to true in the options.ini, the surgeons will still not be highlighted when you play them. 

**To reproduce**
1. Set "elusivesAreShown = true" in options.ini
2. Simply launch the surgeons

**Additional context**
 I know this isn't a personal issue as someone one year ago posted a help post on the discord that went unnoticed. This is a small change but kind of weird considering it went unfound for about a year. Though the problem probably even dates back further than that. (https://discord.com/channels/826809653181808651/1140682112559755396).

It's a very niche thing (People that use peacock --> People that know how to activate highlighted ets --> People with highlighted ets enabled--> People that even started The Surgeons) but still a very strange oversight.

**Comment by RDIL** [comment]
Good catch, known about this one for a while but I keep forgetting about it. It’s because the surgeons have longer form objectives to account for the syringes.

**Comment by MamaLuigiToYou** [comment]
> It’s because the surgeons have longer form objectives to account for the syringes.

Ahhh I see! That makes sense. A lot more complicated then any other simple ET with just a kill objective and maybe a secondary.
