### ISSUE TITLE
Hitman world of assassination saving pop up bug

### ISSUE THREAD

**Issue by TheWrathRF** [thepeacockproject/Peacock#503]
I am on v3.190 game version DODI Repack. If you open the game with Peacock, infinite saving pop up occurs. If you open the game without Peacock the problem does not appear. Latest version also didnt fix the issue.

**Comment by suanjiansalt** [comment]
> I am on v3.190 game version DODI Repack.

As I know the reason you are experiencing problem like this is that you do not own the game. Cracked versions are not and will not be supported.

**Comment by thecatontheceiling** [comment]
Repack versions of HITMAN do not play well with either Peacock or the official servers. Just buy the game, standard edition is on a 60% sale at 28$ USD
