### ISSUE TITLE
Transferring progress gives the purple streak duck instead of the purple streak suit

### ISSUE THREAD

**Issue by thriftydoge** [thepeacockproject/Peacock#514]
**Describe the bug**
If you have a save with the purple streak suit on official servers and you transfer your progress to the peacock server, it will replace the suit with the duck instead.

**To reproduce**
Get a save file with the purple streak suit unlocked and transfer progress the same way as usual.

**Comment by suanjiansalt** [comment]
Purple Streak Suit is rewarded as a challenge reward instead of a crossover bonus so it is locked by default. Purple Streak Duck has not been a reward yet so it'll be shown in inventory by default, along with Purple Suitcase.
