### ISSUE TITLE
Ambrose Island, Shadows in the Water: "Fire-Tempered Hook" not unlocking  

### ISSUE THREAD

**Issue by MisterFloppy** [thepeacockproject/Peacock#524]
I have completed the other challenges of "Butcher's Delight", but I can't complete the "Fire-Tempered Hook" one from Ambrose Island. 

I definitely have fullfilled all the conditions, which are:
- Eliminate Carlton Smith by burning him (-> I used an exploding molotow cocktail to set him on fire)
- eliminate his cell mate with the Hook in Ambrose Island (-> I did so, and also tried it with a smuggled hook from previous game rounds)
- activate the shower

I tried it for multiple times, but "Fire-Tempered Hook" won't unlock! Even if I complete the whole mission by eliminating also the red and blue marked targets, at the end I'm still getting no "Butcher's Delight 1/1" prompt in the summary screen.

So I assume this Peacock special feature is broken.

**Comment by suanjiansalt** [comment]
Why molotov, it's not recognized as a burn accident.

**Comment by Aha00iswr** [comment]
Bro, try to burn Smith by a oil canister. Drop oil beside the cage they are in and when Smith walks over the oil, shoot it. And, throw the hook at the other guy. Activate shower and voila, you got it. 

I also used to throw molotovs like you. But I could complete it after reading the comment of @suanjiansalt

**Comment by MisterFloppy** [comment]
@suanjiansalt:
Since burning Smith directly with a torch didn't work, I tried it by throwing a molotov far enough from him to not let him die by the explosion, but the spreading flames. After reading your comment, I just tried to knock Smith out and drag him to an oil barrel nearby the prison cell and shoot it - but this method doesn't count either.

@Aha00iswr:
Thank you for the hint!
