### ISSUE TITLE
Ambrose Island: "Adding fuel to the fire" challenge completion does not save

### ISSUE THREAD

**Issue by MisterFloppy** [thepeacockproject/Peacock#538]
Using Peacock v7.5.0, I've completed the "Adding fuel to the fire" challenge on Ambrose Island, the checkmark next to the little icon popped up and the challenge was marked as completed. After that, I saved the game, but the next time I loaded from this save slot, the state of the challenge returned to "not completed".

**Comment by AnthonyFuller** [comment]
Great... investigating...

**Comment by suanjiansalt** [comment]
> After that, I saved the game, but the next time I loaded from this save slot, the state of the challenge returned to "not completed"

Sounds more like things about save & load mechanics, if true.

**Comment by AnthonyFuller** [comment]
Yeah, re-created the situation but it's just visual. The challenge properly complete on Peacock.

**Comment by MisterFloppy** [comment]
@AnthonyFuller: Okay, but what does  this mean regarding  "Challenges" and "Profile" statistics of the game? In these sections the "Add fuel to the fire" challenge is still  listed as "incomplete".
