### ISSUE TITLE
Missing reward for completing "Adding fuel to the fire" challenge on Ambrose Island

### ISSUE THREAD

**Issue by MisterFloppy** [thepeacockproject/Peacock#539]
Recently I had problems with completing the "Adding fuel to the fire" challenge on Ambrose Island, because the game would not save the completion state. So I watched some Youtube video how other gamers did it, and finally got it too. But in all videos they were given an oil canister as reward.

Is the reward of the oil canister limited to the official IOI servers and are you planning to implement this item in the future?

**Comment by suanjiansalt** [comment]
As an aside, why do you need to save and load?

**Comment by AnthonyFuller** [comment]
Please provide a debug profile by following these steps;
1. Close the Peacock server window.
2. Open `Tools.cmd` in the Peacock directory.
3. Press Enter.
4. Then attach the `DEBUG_PROFILE.zip` file found in the Peacock directory to a reply here.
**Note:** It is encrypted so only project staff can view the contents.

**Comment by MisterFloppy** [comment]
I've temporarily changed the entry in my options.ini to "enableMasteryProgression = true" to unlock all items just to find out if the oil canister at all is implemented in Peacock 7.5.0. It seems this is not the case.

**Comment by AnthonyFuller** [comment]
The oil canister is implemented fine. I've been using it since it was added in the update in September. Follow the directions in my previous post, otherwise I will be closing this issue.

**Comment by MisterFloppy** [comment]
Okay, I spent a long time on the research and finally found the cause for this issue:  It was a mod from the Nexus Mods website that I had applied before the games' September update and unfortunately forgot to apply after that again. I caught on doing so, the "oil canister" and other item rewards are properly showing up now.

Sorry, I apologize for having caused confusion. Case closed.
