### ISSUE TITLE
7.6.1 version (and 8.0.0 alpha 5) spam messege lags the game

### ISSUE THREAD

**Issue by IKennyAgain** [thepeacockproject/Peacock#547]
**Describe the bug**
 [Info | http] POST /authentication/api/userchannel/EventsService/SaveEvents2
 messege starts to spam in server console, wich lags game significant

**To reproduce**
How can we see the bug on our end? What steps are needed?
bug occured when played freelancer (in some way or another in the mission after performing some activities (killed target, disabled security cams etc) sometimes it not appears) idk if its accured in campaign or contracts

**Additional context**
this messege is spamming 10 times per second, wich represents in server console and log
[peacock-20241229124045.json](https://github.com/user-attachments/files/18269107/peacock-20241229124045.json)

**Comment by thecatontheceiling** [comment]
Some plugin is spamming errors in Peacock. Please undeploy all your mods and try again

**Comment by IKennyAgain** [comment]
> Some plugin is spamming errors in Peacock. Please undeploy all your mods and try again
 
can the saves from previos version of peacock cause issues?

**Comment by suanjiansalt** [comment]
the official server is just remote so you can't see these logs, but they're still there

**Comment by IKennyAgain** [comment]
> Some plugin is spamming errors in Peacock. Please undeploy all your mods and try again

is it any mod  or those wich have plugins in them?

**Comment by IKennyAgain** [comment]
ok so when i starting game and peacock i have this messege

[Warn | Contracts] Game version not specified. This plugin needs to be updated! Assuming h3.

**Comment by IKennyAgain** [comment]
OK i found issue so the Peacock Plus mod is causing that

**Comment by RDIL** [comment]
Yeah, this is either a mod or a game bug.
