### ISSUE TITLE
Support H3 ghost mode

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#6]
- [ ] Add support for ghost mode in H3

**Comment by AnthonyFuller** [comment]
What is needed to support this? Is it the menu options?

**Comment by RDIL** [comment]
I'm not sure if it shows up in the menus because h2 has specific overrides within this codebase. Not 100% sure though, will try and get someone to test it.

**Comment by AnthonyFuller** [comment]
Well, we shouldn't care about that, mods should add that as for H3, it's the only way it'll work.

**Comment by AnthonyFuller** [comment]
Don't believe so, Heritage UI for example only shows the Sniper Multiplayer UI options on non-official Steam servers.
