### ISSUE TITLE
Different challenges for different games

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#93]
- Original thread: https://discord.com/channels/826809653181808651/1067796022199332890
- Originally tracked in #90. It now has its own issue because it was not introduced by v6 since it already existed in v5, and getting it fixed before v6 releases might not be a priority. 
- This bug arises from challenges belonging in different categories in different game versions.
  - E.g. in H1, "The Classics" challenges like silent assassin are in the "assassination" category. 
  - For each location, we might need a separate "challenges.json" file for each game version in the future. 
- [x] Add challenges data in `json` files for all three games.
- [x] Support looking up challenges using game version.
- [x] Support difficulty-aware challenges in H1 & H2.

**Comment by AnthonyFuller** [comment]
> For each location, we might need a separate "challenges.json" file for each game version in the future.

This is most likely the ideal solution.
